name: Le Bon Vivant Media
favicon: null
layout_spectrum: 0.2247121357358992
typography_spectrum: 0.22860855259932578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202a45'
    - '#717c3a'
    - '#ffffff'
    - '#9f3050'
    - '#d7b345'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
