name: Le Bon Vivant Media
favicon: null
layout_spectrum: 0.2247121357358992
typography_spectrum: 0.22860855259932578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40161800663918257
  lightness: 0.707546349382028
  saturation: 0.8951908487360924
  rhythmicContrast: 0.9562301395926625
purpose: []
